language: generic

env:
  global:
    - PYTHONIOENCODING=UTF8
    - MPLBACKEND=Agg

matrix:
  include:
    - os: linux
      language: generic
      env:
        - PYTHON_VERSION=3.6
        - CONDA=true

    - os: linux
      language: generic
      env:
        - PYTHON_VERSION=3.7
        - CONDA=true

before_install:
  - curl -sSfL -o data.zip https://nextcloud.e5.physik.tu-dortmund.de/index.php/s/Cstsf8MWZjnz92L/download
  - unzip data.zip
  - mv eventdisplay_dl2 data
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - . $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda  # get latest conda version
  - conda info -a # Useful for debugging any issues with conda

install:
  - sed -i -e "s/- python=.*/- python=$PYTHON_VERSION/g" environment.yml
  - conda env create -f environment.yml
  - conda activate pyirf-dev
  # cython needed for building gammapy
  - pip install travis-sphinx codecov pytest-cov Cython
  - pip install .[all]
  - python --version

script:
  - pytest --cov=pyirf --cov-report=xml
  - python examples/calculate_eventdisplay_irfs.py
  - travis-sphinx -v --outdir=docbuild build --source=docs/

after_script:
  - if [[ "$CONDA" == "true" ]];then
        conda deactivate
    fi
  - python setup.py build_sphinx

after_success:
  - codecov
  - travis-sphinx -v --outdir=docbuild deploy
