# A conda environment with all useful package for ctapipe developers
name: pyirf-dev

channels:
  - default
dependencies:
  - python=3.7
  - astropy
  - numpy
  - ipython
  - jupyter
  - matplotlib
  - scipy
  - setuptools
  # tests
  - pytest
  - pytest-cov
  # docs
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
      - nbsphinx
      - sphinx_automodapi
      - uproot~=3.0
