name: pyirf

channels:
  - default
  - conda-forge
dependencies:
  - python=3.7
  - numpy
  - ipython
  - jupyter
  - matplotlib
  - scipy
  - astropy>=4.0.2,<5
  - setuptools
  - tqdm
  # tests
  - pytest
  - pytest-cov
  # docs
  - numpydoc
  - pytables
  - nbsphinx
  - sphinx
  - sphinx_rtd_theme
  - sphinx_automodapi
  - uproot=4
  - awkward=1
  - gammapy=0.18
  - pip
  - pip:
    - gammapy~=0.19.0
    - ogadf_schema
