# A conda environment with all useful package for ctapipe developers
name: pyrf
channels:
  - default
  - cta-observatory
dependencies:
  - astropy
  - conda-forge::nbsphinx
  - cython
  - ipython
  - joblib
  - jupyter
  - matplotlib
  - numba
  - numpy>=1.15.4
  - numpydoc
  - pandas
  - pytables
  - pytest
  - pyyaml
  - scipy
  - setuptools
  - sphinx
  - sphinx-automodapi
  - sphinx_rtd_theme
  - pip
pip:
  - rinohtype


